In [13]:
!pip install --upgrade pip
!pip install -q -r requirements.txt

Requirement already satisfied: pip in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (22.3.1)

In [ ]:
# !pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

In [10]:
!pwd #current Directory

/workspace/Player_Performance_Prediction

In [49]:
import pandas as pd
import numpy as np

In [81]:
data = pd.read_csv("/workspace/Player_Performance_Prediction/Demo/335982.csv")
df = data.copy()

In [82]:
# df.head()
df = df.fillna(0)
df.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [83]:
#checking the data types 
df.dtypes

match_id                    int64
season                     object
start_date                 object
venue                      object
innings                     int64
ball                      float64
batting_team               object
bowling_team               object
striker                    object
non_striker                object
bowler                     object
runs_off_bat                int64
extras                      int64
wides                     float64
noballs                   float64
byes                      float64
legbyes                   float64
penalty                   float64
wicket_type                object
player_dismissed           object
other_wicket_type         float64
other_player_dismissed    float64
dtype: object

In [84]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

### Copying the below columns same as it is

'match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
'batting_team', 'bowling_team', 'striker'

### Combine below columns into one column
'extras', 'wides', 'noballs', 'byes', 'legbyes',

### check below
 'penalty'

### use Feature enginneering on it to convert bolwer_dismmised
'wicket_type', 'player_dismissed',

### drop after checking its value
'other_wicket_type',
       'other_player_dismissed'

In [85]:
df.shape

(225, 22)

In [86]:
df.penalty.nunique()

1

In [87]:
runs_not_from_the_bat = df['extras'] + df['wides'] + df['noballs'] + df['byes'] + df['legbyes']
df['runs_not_from_bat'] = runs_not_from_the_bat
df = df.drop(['other_player_dismissed','other_wicket_type'],axis=1)
df = df.drop(['extras','wides','noballs','byes','legbyes'],axis=1) 
df.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,penalty,wicket_type,player_dismissed,runs_not_from_bat
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,0.0,0,0,2.0
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0.0,0,0,0.0
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0.0,0,0,2.0
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0.0,0,0,0.0
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0.0,0,0,0.0

In [88]:
df = df.drop(['penalty'],axis=1)

In [89]:
df.head(5)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,wicket_type,player_dismissed,runs_not_from_bat
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,0,0,2.0
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0.0
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,2.0
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0.0
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0.0

In [90]:
# data.tail()

In [91]:
df.shape

(225, 15)

In [92]:
df.player_dismissed.unique()

array([0, 'SC Ganguly', 'RT Ponting', 'DJ Hussey', 'R Dravid', 'V Kohli',
       'JH Kallis', 'W Jaffer', 'MV Boucher', 'B Akhil', 'CL White',
       'AA Noffke', 'Z Khan', 'SB Joshi'], dtype=object)

In [93]:
total_runs = pd.DataFrame(df.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum()).\
       rename(columns={"runs_off_bat": "Batsman_runs"})

#number of sixes
sixes = pd.DataFrame(df[df['runs_off_bat'] == 6].groupby(['batting_team','bowling_team','match_id', 'striker'])['runs_off_bat'].count()).\
            rename(columns={"runs_off_bat": "6"})

#number of fours
fours = pd.DataFrame(df[df['runs_off_bat'] == 4].groupby(['batting_team','bowling_team','match_id', 'striker'])['runs_off_bat'].count()).\
            rename(columns={"runs_off_bat": "4"})

#no of balls
balls_faced = pd.DataFrame(df.groupby(['batting_team','bowling_team','match_id', 'striker'])['ball'].nunique()).\
            rename(columns={"ball": "total_legal_balls_faced"})

#strikerate
Strikerate = pd.DataFrame((df.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum()/df.groupby(['batting_team','bowling_team','match_id', 'striker'])['ball'].nunique())*100).\
       rename(columns={"runs_off_bat":"strike_rate"})


#fifties
fifties = pd.DataFrame((df.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum() >= 50)  
                       ).\
       rename(columns={"runs_off_bat": "50"})
#hundreds
hundreds = pd.DataFrame(df.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum() >= 100  ).\
       rename(columns={"scorevalue": "100"})

#duck
duck  = pd.DataFrame(df.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum() == 0).\
        rename(columns={"runs_off_bat": "duck"})

# #batsmen_position
# batsmen_position = pd.DataFrame(df_2021.groupby(['battingteam','bowlingteam','matchid', 'batsmanname'])['fallofwickets'].min())

#batting_team
# batting_team = pd.DataFrame(df_2021['battingteam'])

# batting_team
# bowling_team = pd.DataFrame(df_2021['bowlingteam'])

In [100]:
# total_runs.Batsman_runs
# hundreds
# fifties
# batsmen_Strikerate
# sixes
# Strikerate.0

In [107]:
# Strikerate.to_csv('Sr.csv')
sr = pd.read_csv("/workspace/Player_Performance_Prediction/Sr.csv")
# sr.0.values()

SyntaxError: invalid syntax (2472586734.py, line 3)

In [108]:

total_runs['Balls'] = balls_faced
total_runs['Fours'] = batsmen_scores4
total_runs['Sixes'] = batsmen_scores6
# total_runs['SR'] = sr['0']
total_runs['Fifties'] = fifties
total_runs['Hundreds'] = hundreds
total_runs['Duck'] = duck

In [112]:
# sr['0']
total_runs = total_runs.drop(['SR'],axis=1)

In [113]:
total_runs.head()

                                                                            Batsman_runs  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum               158
                                                           DJ Hussey                  12
                                                           Mohammad Hafeez             5
                                                           RT Ponting                 20
                                                           SC Ganguly                 10

                                                                            Balls  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum         77
                                                           DJ Hussey           12
                                                           Mohammad Hafeez      3
                                                           RT Ponting          20
                                                           SC Ganguly          12

                                                                            Fours  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum       10.0
                                                           DJ Hussey          1.0
                                                           Mohammad Hafeez    1.0
                                                           RT Ponting         1.0
                                                           SC Ganguly         2.0

                                                                            Sixes  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum       13.0
                                                           DJ Hussey          NaN
                                                           Mohammad Hafeez    NaN
                                                           RT Ponting         1.0
                                                           SC Ganguly         NaN

                                                                            Fifties  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum         True
                                                           DJ Hussey          False
                                                           Mohammad Hafeez    False
                                                           RT Ponting         False
                                                           SC Ganguly         False

                                                                            Hundreds  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum          True
                                                           DJ Hussey           False
                                                           Mohammad Hafeez     False
                                                           RT Ponting          False
                                                           SC Ganguly          False

                                                                             Duck
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum      False
                                                           DJ Hussey        False
                                                           Mohammad Hafeez  False
                                                           RT Ponting       False
                                                           SC Ganguly       False

In [114]:
df1 = total_runs.copy()
df1.Hundreds = df.Hundreds.replace({True: 1, False: 0})
df.Fifties = df.Fifties.replace({True: 1, False: 0})
df.Duck = df.Duck.replace({True: 1, False: 0})
df.Sixes = df.Sixes.replace({True: 1, False: 0})
df = df.fillna(0)

AttributeError: 'DataFrame' object has no attribute 'Hundreds'