In [2]:
!pip install --upgrade pip
!pip install -q -r requirements.txt

Requirement already satisfied: pip in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (22.3.1)

In [ ]:
# !pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

In [3]:
!pwd #current Directory

/workspace/Player_Performance_Prediction

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("/workspace/Player_Performance_Prediction/Demo/335982.csv",low_memory=False)
data = df.copy()

In [6]:
data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# df.head()
data = data.fillna(0)
data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [8]:
#checking the data types 
data.dtypes

match_id                    int64
season                     object
start_date                 object
venue                      object
innings                     int64
ball                      float64
batting_team               object
bowling_team               object
striker                    object
non_striker                object
bowler                     object
runs_off_bat                int64
extras                      int64
wides                     float64
noballs                   float64
byes                      float64
legbyes                   float64
penalty                   float64
wicket_type                object
player_dismissed           object
other_wicket_type         float64
other_player_dismissed    float64
dtype: object

In [9]:
data.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

### Copying the below columns same as it is

'match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
'batting_team', 'bowling_team', 'striker'

### Combine below columns into one column
'extras', 'wides', 'noballs', 'byes', 'legbyes',

### check below
 'penalty'

### use Feature enginneering on it to convert bolwer_dismmised
'wicket_type', 'player_dismissed',

### drop after checking its value
'other_wicket_type',
       'other_player_dismissed'

In [11]:
data.shape

(225, 22)

In [12]:
data.penalty.nunique()

1

In [31]:
runs_not_from_the_bat = data['extras'] + data['wides'] + data['noballs'] + data['byes'] + data['legbyes']
# df1['runs_not_from_bat'] = runs_not_from_the_bat
# data['runs_not_from_bat'] = runs_not_from_the_bat
# data = data.drop(['other_player_dismissed','other_wicket_type'],axis=1)
# data = data.drop(['extras','wides','noballs','byes','legbyes'],axis=1) 
# data = data.drop(['penalty'],axis=1)
# df1.head()
runs_not_from_the_bat

0      2.0
1      0.0
2      2.0
3      0.0
4      0.0
      ...
220    2.0
221    0.0
222    0.0
223    2.0
224    0.0
Length: 225, dtype: float64

In [11]:
df.head(5)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,wicket_type,player_dismissed,runs_not_from_bat
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,0,0,2.0
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0.0
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,2.0
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0.0
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0.0

In [12]:
# data.tail()

In [13]:
df.shape

(225, 15)

In [32]:
data.player_dismissed.unique()

array([0, 'SC Ganguly', 'RT Ponting', 'DJ Hussey', 'R Dravid', 'V Kohli',
       'JH Kallis', 'W Jaffer', 'MV Boucher', 'B Akhil', 'CL White',
       'AA Noffke', 'Z Khan', 'SB Joshi'], dtype=object)

In [33]:
data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [37]:
total_runs = pd.DataFrame(data.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum()).\
       rename(columns={"runs_off_bat": "Batsman_runs"})

#number of sixes
sixes = pd.DataFrame(data[data['runs_off_bat'] == 6].groupby(['batting_team','bowling_team','match_id', 'striker'])['runs_off_bat'].count()).\
            rename(columns={"runs_off_bat": "6"})

#number of fours
fours = pd.DataFrame(data[data['runs_off_bat'] == 4].groupby(['batting_team','bowling_team','match_id', 'striker'])['runs_off_bat'].count()).\
            rename(columns={"runs_off_bat": "4"})

#no of balls
balls_faced = pd.DataFrame(data.groupby(['batting_team','bowling_team','match_id', 'striker'])['ball'].nunique()).\
            rename(columns={"ball": "total_legal_balls_faced"})

#strikerate
Strikerate = pd.DataFrame((data.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum()/data.groupby(['batting_team','bowling_team','match_id', 'striker'])['ball'].nunique())*100).\
       rename(columns={"runs_off_bat":"strike_rate"})


#fifties
fifties = pd.DataFrame((data.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum() >= 50)  
                       ).\
       rename(columns={"runs_off_bat": "50"})
#hundreds
hundreds = pd.DataFrame(data.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum() >= 100  ).\
       rename(columns={"runs_off_bat": "100"})

#duck
duck  = pd.DataFrame(data.groupby(['batting_team','bowling_team','match_id','striker'])['runs_off_bat'].sum() == 0).\
        rename(columns={"runs_off_bat": "duck"})

# #batsmen_position
# batsmen_position = pd.DataFrame(df_2021.groupby(['battingteam','bowlingteam','matchid', 'batsmanname'])['fallofwickets'].min())

#batting_team
# batting_team = pd.DataFrame(df_2021['battingteam'])

# batting_team
# bowling_team = pd.DataFrame(df_2021['bowlingteam'])

In [56]:
# total_runs
# hundreds
# fifties
# batsmen_Strikerate
# sixes
# fours
# Strikerate
# runs_not_from_the_bat = pd.DataFrame(runs_not_from_the_bat)
# runs_not_from_the_bat.to_csv("Extras.csv")

In [57]:
# Strikerate.to_csv('Sr.csv')
# sr = pd.read_csv("/workspace/Player_Performance_Prediction/Sr.csv")
# sr.0.values()
Extras = pd.read_csv("/workspace/Player_Performance_Prediction/Extras.csv")

In [66]:
# total_runs
Extras['0']

0      2.0
1      0.0
2      2.0
3      0.0
4      0.0
      ...
220    2.0
221    0.0
222    0.0
223    2.0
224    0.0
Name: 0, Length: 225, dtype: float64

In [64]:

total_runs['Balls'] = balls_faced
total_runs['Fours'] = fours
total_runs['Sixes'] = sixes
# total_runs['SR'] = sr['0']
total_runs['Fifties'] = fifties
total_runs['Hundreds'] = hundreds
total_runs['Duck'] = duck
total_runs['Extras'] = Extras['0']

In [63]:
total_runs

                                                                                  Batsman_runs
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum               158
                                                                 DJ Hussey                  12
                                                                 Mohammad Hafeez             5
                                                                 RT Ponting                 20
                                                                 SC Ganguly                 10
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke                   9
                                                                 B Akhil                     0
                                                                 CL White                    6
                                                                 JH Kallis                   8
                                                                 MV Boucher                  7
                                                                 P Kumar                    18
                                                                 R Dravid                    2
                                                                 SB Joshi                    3
                                                                 V Kohli                     1
                                                                 W Jaffer                    6
                                                                 Z Khan                      3

In [68]:
Extras.shape

(225, 2)

In [69]:
total_runs = total_runs.fillna(0)
total_runs

                                                                                  Batsman_runs  \
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum               158
                                                                 DJ Hussey                  12
                                                                 Mohammad Hafeez             5
                                                                 RT Ponting                 20
                                                                 SC Ganguly                 10
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke                   9
                                                                 B Akhil                     0
                                                                 CL White                    6
                                                                 JH Kallis                   8
                                                                 MV Boucher                  7
                                                                 P Kumar                    18
                                                                 R Dravid                    2
                                                                 SB Joshi                    3
                                                                 V Kohli                     1
                                                                 W Jaffer                    6
                                                                 Z Khan                      3

                                                                                  Balls  \
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum         77
                                                                 DJ Hussey           12
                                                                 Mohammad Hafeez      3
                                                                 RT Ponting          20
                                                                 SC Ganguly          12
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke           12
                                                                 B Akhil              2
                                                                 CL White            10
                                                                 JH Kallis            7
                                                                 MV Boucher          11
                                                                 P Kumar             17
                                                                 R Dravid             3
                                                                 SB Joshi             8
                                                                 V Kohli              5
                                                                 W Jaffer            18
                                                                 Z Khan               8

                                                                                  Fours  \
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum       10.0
                                                                 DJ Hussey          1.0
                                                                 Mohammad Hafeez    1.0
                                                                 RT Ponting         1.0
                                                                 SC Ganguly         2.0
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke          1.0
                                                                 B Akhil            0.0
                                                                 CL White           0.0
                                                                 JH Kallis          0.0
                                                                 MV Boucher         1.0
                                                                 P Kumar            1.0
                                                                 R Dravid           0.0
                                                                 SB Joshi           0.0
                                                                 V Kohli            0.0
                                                                 W Jaffer           0.0
                                                                 Z Khan             0.0

                                                                                  Sixes  \
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum       13.0
                                                                 DJ Hussey          0.0
                                                                 Mohammad Hafeez    0.0
                                                                 RT Ponting         1.0
                                                                 SC Ganguly         0.0
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke          0.0
                                                                 B Akhil            0.0
                                                                 CL White           0.0
                                                                 JH Kallis          1.0
                                                                 MV Boucher         0.0
                                                                 P Kumar            2.0
                                                                 R Dravid           0.0
                                                                 SB Joshi           0.0
                                                                 V Kohli            0.0
                                                                 W Jaffer           0.0
                                                                 Z Khan             0.0

                                                                                  Fifties  \
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum         True
                                                                 DJ Hussey          False
                                                                 Mohammad Hafeez    False
                                                                 RT Ponting         False
                                                                 SC Ganguly         False
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke          False
                                                                 B Akhil            False
                                                                 CL White           False
                                                                 JH Kallis          False
                                                                 MV Boucher         False
                                                                 P Kumar            False
                                                                 R Dravid           False
                                                                 SB Joshi           False
                                                                 V Kohli            False
                                                                 W Jaffer           False
                                                                 Z Khan             False

                                                                                  Hundreds  \
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum          True
                                                                 DJ Hussey           False
                                                                 Mohammad Hafeez     False
                                                                 RT Ponting          False
                                                                 SC Ganguly          False
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke           False
                                                                 B Akhil             False
                                                                 CL White            False
                                                                 JH Kallis           False
                                                                 MV Boucher          False
                                                                 P Kumar             False
                                                                 R Dravid            False
                                                                 SB Joshi            False
                                                                 V Kohli             False
                                                                 W Jaffer            False
                                                                 Z Khan              False

                                                                                   Duck  \
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum      False
                                                                 DJ Hussey        False
                                                                 Mohammad Hafeez  False
                                                                 RT Ponting       False
                                                                 SC Ganguly       False
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke        False
                                                                 B Akhil           True
                                                                 CL White         False
                                                                 JH Kallis        False
                                                                 MV Boucher       False
                                                                 P Kumar          False
                                                                 R Dravid         False
                                                                 SB Joshi         False
                                                                 V Kohli          False
                                                                 W Jaffer         False
                                                                 Z Khan           False

                                                                                  Extras
batting_team                bowling_team                match_id striker
Kolkata Knight Riders       Royal Challengers Bangalore 335982   BB McCullum         0.0
                                                                 DJ Hussey           0.0
                                                                 Mohammad Hafeez     0.0
                                                                 RT Ponting          0.0
                                                                 SC Ganguly          0.0
Royal Challengers Bangalore Kolkata Knight Riders       335982   AA Noffke           0.0
                                                                 B Akhil             0.0
                                                                 CL White            0.0
                                                                 JH Kallis           0.0
                                                                 MV Boucher          0.0
                                                                 P Kumar             0.0
                                                                 R Dravid            0.0
                                                                 SB Joshi            0.0
                                                                 V Kohli             0.0
                                                                 W Jaffer            0.0
                                                                 Z Khan              0.0

In [77]:
# sr['0']
# total_runs = total_runs.drop(['SR'],axis=1)

In [20]:
total_runs.head()

                                                                            Batsman_runs  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum               158
                                                           DJ Hussey                  12
                                                           Mohammad Hafeez             5
                                                           RT Ponting                 20
                                                           SC Ganguly                 10

                                                                            Balls  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum         77
                                                           DJ Hussey           12
                                                           Mohammad Hafeez      3
                                                           RT Ponting          20
                                                           SC Ganguly          12

                                                                            Fours  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum       10.0
                                                           DJ Hussey          1.0
                                                           Mohammad Hafeez    1.0
                                                           RT Ponting         1.0
                                                           SC Ganguly         2.0

                                                                            Sixes  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum       13.0
                                                           DJ Hussey          NaN
                                                           Mohammad Hafeez    NaN
                                                           RT Ponting         1.0
                                                           SC Ganguly         NaN

                                                                            Fifties  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum         True
                                                           DJ Hussey          False
                                                           Mohammad Hafeez    False
                                                           RT Ponting         False
                                                           SC Ganguly         False

                                                                            Hundreds  \
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum          True
                                                           DJ Hussey           False
                                                           Mohammad Hafeez     False
                                                           RT Ponting          False
                                                           SC Ganguly          False

                                                                             Duck
batting_team          bowling_team                match_id striker
Kolkata Knight Riders Royal Challengers Bangalore 335982   BB McCullum      False
                                                           DJ Hussey        False
                                                           Mohammad Hafeez  False
                                                           RT Ponting       False
                                                           SC Ganguly       False

In [76]:
df1 = total_runs.copy()

In [ ]:
# df1 =

In [79]:
# df1.head()
df1.Hundreds = df1.Hundreds.replace({True: 1, False: 0})
df1.Fifties = df1.Fifties.replace({True: 1, False: 0})
df1.Duck = df1.Duck.replace({True: 1, False: 0})
df1.Sixes = df1.Sixes.replace({True: 1, False: 0})
# df = df.fillna(0)

In [81]:
df1.to_csv("df.csv")

In [85]:
sample = pd.read_csv("/workspace/Player_Performance_Prediction/df.csv")
sample.head(2)

,batting_team,bowling_team,match_id,striker,Batsman_runs,Balls,Fours,Sixes,Fifties,Hundreds,Duck,Extras
0,Kolkata Knight Riders,Royal Challengers Bangalore,335982,BB McCullum,158,77,10.0,13.0,1,1,0,0.0
1,Kolkata Knight Riders,Royal Challengers Bangalore,335982,DJ Hussey,12,12,1.0,0.0,0,0,0,0.0

In [87]:
#point system of dream11
  # pointsconfig = {
  #       'total_runs': 1,
  #       'run_6': 2,
  #       'run_4': 1,
  #       '>=50': 8,
  #       '>=100': 16,
  #       'duck': -2,
  # }

dreamll_score = sample['Batsman_runs'] + sample['Sixes']*2 + sample['Fours'] + sample['Fifties']*8 + sample['Hundreds']*16 - sample['Duck']*2 + 4
sample['dreamll_score'] = dreamll_score

In [89]:
sample = sample.drop(['Extras'],axis=1)
sample

,batting_team,bowling_team,match_id,striker,Batsman_runs,Balls,Fours,Sixes,Fifties,Hundreds,Duck,dreamll_score
0,Kolkata Knight Riders,Royal Challengers Bangalore,335982,BB McCullum,158,77,10.0,13.0,1,1,0,222.0
1,Kolkata Knight Riders,Royal Challengers Bangalore,335982,DJ Hussey,12,12,1.0,0.0,0,0,0,17.0
2,Kolkata Knight Riders,Royal Challengers Bangalore,335982,Mohammad Hafeez,5,3,1.0,0.0,0,0,0,10.0
3,Kolkata Knight Riders,Royal Challengers Bangalore,335982,RT Ponting,20,20,1.0,1.0,0,0,0,27.0
4,Kolkata Knight Riders,Royal Challengers Bangalore,335982,SC Ganguly,10,12,2.0,0.0,0,0,0,16.0
5,Royal Challengers Bangalore,Kolkata Knight Riders,335982,AA Noffke,9,12,1.0,0.0,0,0,0,14.0
6,Royal Challengers Bangalore,Kolkata Knight Riders,335982,B Akhil,0,2,0.0,0.0,0,0,1,2.0
7,Royal Challengers Bangalore,Kolkata Knight Riders,335982,CL White,6,10,0.0,0.0,0,0,0,10.0
8,Royal Challengers Bangalore,Kolkata Knight Riders,335982,JH Kallis,8,7,0.0,1.0,0,0,0,14.0
9,Royal Challengers Bangalore,Kolkata Knight Riders,335982,MV Boucher,7,11,1.0,0.0,0,0,0,12.0
10,Royal Challengers Bangalore,Kolkata Knight Riders,335982,P Kumar,18,17,1.0,2.0,0,0,0,27.0
11,Royal Challengers Bangalore,Kolkata Knight Riders,335982,R Dravid,2,3,0.0,0.0,0,0,0,6.0
12,Royal Challengers Bangalore,Kolkata Knight Riders,335982,SB Joshi,3,8,0.0,0.0,0,0,0,7.0
13,Royal Challengers Bangalore,Kolkata Knight Riders,335982,V Kohli,1,5,0.0,0.0,0,0,0,5.0
14,Royal Challengers Bangalore,Kolkata Knight Riders,335982,W Jaffer,6,18,0.0,0.0,0,0,0,10.0
15,Royal Challengers Bangalore,Kolkata Knight Riders,335982,Z Khan,3,8,0.0,0.0,0,0,0,7.0

In [91]:
sample1 = sample.copy()
sample2 = sample.copy()
# sample3 = sample1 + sample2
# sample3
sa = pd.concat([sample1,sample2])

In [92]:
sa

,batting_team,bowling_team,match_id,striker,Batsman_runs,Balls,Fours,Sixes,Fifties,Hundreds,Duck,dreamll_score
0,Kolkata Knight Riders,Royal Challengers Bangalore,335982,BB McCullum,158,77,10.0,13.0,1,1,0,222.0
1,Kolkata Knight Riders,Royal Challengers Bangalore,335982,DJ Hussey,12,12,1.0,0.0,0,0,0,17.0
2,Kolkata Knight Riders,Royal Challengers Bangalore,335982,Mohammad Hafeez,5,3,1.0,0.0,0,0,0,10.0
3,Kolkata Knight Riders,Royal Challengers Bangalore,335982,RT Ponting,20,20,1.0,1.0,0,0,0,27.0
4,Kolkata Knight Riders,Royal Challengers Bangalore,335982,SC Ganguly,10,12,2.0,0.0,0,0,0,16.0
5,Royal Challengers Bangalore,Kolkata Knight Riders,335982,AA Noffke,9,12,1.0,0.0,0,0,0,14.0
6,Royal Challengers Bangalore,Kolkata Knight Riders,335982,B Akhil,0,2,0.0,0.0,0,0,1,2.0
7,Royal Challengers Bangalore,Kolkata Knight Riders,335982,CL White,6,10,0.0,0.0,0,0,0,10.0
8,Royal Challengers Bangalore,Kolkata Knight Riders,335982,JH Kallis,8,7,0.0,1.0,0,0,0,14.0
9,Royal Challengers Bangalore,Kolkata Knight Riders,335982,MV Boucher,7,11,1.0,0.0,0,0,0,12.0
10,Royal Challengers Bangalore,Kolkata Knight Riders,335982,P Kumar,18,17,1.0,2.0,0,0,0,27.0
11,Royal Challengers Bangalore,Kolkata Knight Riders,335982,R Dravid,2,3,0.0,0.0,0,0,0,6.0
12,Royal Challengers Bangalore,Kolkata Knight Riders,335982,SB Joshi,3,8,0.0,0.0,0,0,0,7.0
13,Royal Challengers Bangalore,Kolkata Knight Riders,335982,V Kohli,1,5,0.0,0.0,0,0,0,5.0
14,Royal Challengers Bangalore,Kolkata Knight Riders,335982,W Jaffer,6,18,0.0,0.0,0,0,0,10.0
15,Royal Challengers Bangalore,Kolkata Knight Riders,335982,Z Khan,3,8,0.0,0.0,0,0,0,7.0
0,Kolkata Knight Riders,Royal Challengers Bangalore,335982,BB McCullum,158,77,10.0,13.0,1,1,0,222.0
1,Kolkata Knight Riders,Royal Challengers Bangalore,335982,DJ Hussey,12,12,1.0,0.0,0,0,0,17.0
2,Kolkata Knight Riders,Royal Challengers Bangalore,335982,Mohammad Hafeez,5,3,1.0,0.0,0,0,0,10.0
3,Kolkata Knight Riders,Royal Challengers Bangalore,335982,RT Ponting,20,20,1.0,1.0,0,0,0,27.0
4,Kolkata Knight Riders,Royal Challengers Bangalore,335982,SC Ganguly,10,12,2.0,0.0,0,0,0,16.0
5,Royal Challengers Bangalore,Kolkata Knight Riders,335982,AA Noffke,9,12,1.0,0.0,0,0,0,14.0
6,Royal Challengers Bangalore,Kolkata Knight Riders,335982,B Akhil,0,2,0.0,0.0,0,0,1,2.0
7,Royal Challengers Bangalore,Kolkata Knight Riders,335982,CL White,6,10,0.0,0.0,0,0,0,10.0
8,Royal Challengers Bangalore,Kolkata Knight Riders,335982,JH Kallis,8,7,0.0,1.0,0,0,0,14.0
9,Royal Challengers Bangalore,Kolkata Knight Riders,335982,MV Boucher,7,11,1.0,0.0,0,0,0,12.0
10,Royal Challengers Bangalore,Kolkata Knight Riders,335982,P Kumar,18,17,1.0,2.0,0,0,0,27.0
11,Royal Challengers Bangalore,Kolkata Knight Riders,335982,R Dravid,2,3,0.0,0.0,0,0,0,6.0
12,Royal Challengers Bangalore,Kolkata Knight Riders,335982,SB Joshi,3,8,0.0,0.0,0,0,0,7.0
13,Royal Challengers Bangalore,Kolkata Knight Riders,335982,V Kohli,1,5,0.0,0.0,0,0,0,5.0
14,Royal Challengers Bangalore,Kolkata Knight Riders,335982,W Jaffer,6,18,0.0,0.0,0,0,0,10.0
15,Royal Challengers Bangalore,Kolkata Knight Riders,335982,Z Khan,3,8,0.0,0.0,0,0,0,7.0

In [ ]:
import os
import pandas as pd

# Specify the input and output folders
input_folder = "path/to/input/folder"
output_folder = "path/to/output/folder"

# Iterate through all files in the input folder
for file in os.listdir(input_folder):
  # Only consider CSV files
  if file.endswith(".csv"):
    # Read in the CSV file
    df = pd.read_csv(os.path.join(input_folder, file))

    # Perform some operations on the dataframe, such as filtering rows or calculating values

    # Save the modified dataframe to a new CSV file in the output folder
    df.to_csv(os.path.join(output_folder, file), index=False)

In [ ]:
import os
import pandas as pd

# Specify the folder containing the CSV files
folder = "path/to/folder"

# Initialize an empty list to store the dataframes
df_list = []

# Iterate through all files in the folder
for file in os.listdir(folder):
  # Only consider CSV files
  if file.endswith(".csv"):
    # Read in the CSV file
    df = pd.read_csv(os.path.join(folder, file))
    # Add the dataframe to the list
    df_list.append(df)

# Concatenate all dataframes into a single dataframe
df = pd.concat(df_list)

# Write the combined data to a new CSV file
df.to_csv("combined_file.csv", index=False)